# Generated by Django 5.2.9 on 2026-01-03 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartialResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(db_index=True, max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("last_section_id", models.UUIDField(blank=True, null=True)),
                ("last_field_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partial_responses",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partial_survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "partial_responses",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["survey", "session_token"],
                        name="partial_res_survey__0ad956_idx",
                    ),
                    models.Index(
                        fields=["session_token"], name="partial_res_session_93fb15_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="partial_res_last_up_b098c9_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "session_token"), name="unique_survey_session"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("encrypted_data", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "completion_time_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "responses",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["survey"], name="responses_survey__edb083_idx"
                    ),
                    models.Index(fields=["user"], name="responses_user_id_bf83a4_idx"),
                    models.Index(
                        fields=["survey", "user"], name="responses_survey__4814aa_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="responses_submitt_f56fdd_idx"
                    ),
                ],
            },
        ),
    ]
