# Generated by Django 5.2.9 on 2026-01-04 17:07
# Custom migration to handle organization field conversion

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # Step 1: Create Organization model
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        
        # Step 2: Rename old organization field
        migrations.RenameField(
            model_name="user",
            old_name="organization",
            new_name="organization_old",
        ),
        
        # Step 3: Add new organization ForeignKey field (nullable)
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.organization",
            ),
        ),
        
        # Step 4: Remove old organization_old field
        migrations.RemoveField(
            model_name="user",
            name="organization_old",
        ),
    ]
