# Generated by Django 5.2.9 on 2026-01-03 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("logic_rules", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "db_table": "sections",
                "ordering": ["survey", "order"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multi-Select"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkbox"),
                            ("rating", "Rating Scale"),
                            ("file", "File Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("help_text", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_required", models.BooleanField(default=False)),
                ("validation_regex", models.CharField(blank=True, max_length=500)),
                ("validation_message", models.CharField(blank=True, max_length=255)),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                ("logic_rules", models.JSONField(blank=True, default=dict)),
                ("dependency_config", models.JSONField(blank=True, default=dict)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="surveys.section",
                    ),
                ),
            ],
            options={
                "db_table": "fields",
                "ordering": ["section", "order"],
                "indexes": [
                    models.Index(
                        fields=["section", "order"], name="fields_section_55b349_idx"
                    ),
                    models.Index(
                        fields=["field_type"], name="fields_field_t_6c94f8_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["owner"], name="surveys_owner_i_0f0e11_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["is_active"], name="surveys_is_acti_55133e_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["created_at"], name="surveys_created_4cecc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["survey", "order"], name="sections_survey__d99547_idx"
            ),
        ),
    ]
